#! /usr/bin/env bash

# Get Username

echo -n "Please enter your GitHub username [ENTER]: "
read username

# Get Password

echo -n "Please enter your password [ENTER]: "
read password

# Get Folder Name

folder=`basename "$PWD"`
folder_=`echo ${folder// /_}`

# Delete Remote Repository on github.com

curl -u '$username:$password' -X "DELETE" https://api.github.com/repos/$username/$folder_

# Create Remote Repository on gitHub.com

curl -u '$username:$password' https://api.github.com/user/repos -d "{\"name\":\"$folder_\"}" 

# Generate Local Git Repository

git init

# Create .gitignore File

echo "
# $folder_ gitignore

# Ignore everything
*

# Now, whitelist anything that's a directory
!*/

# But not these files
!*.R
!*.py
!*.sql
!*.sas
!*.sh
!*.bat
!*.gitignore
!*.md
" >> .gitignore

# Ignore files w/ Size > 5M

find . -size +5M | sed 's|^\./||g' | cat >> .gitignore

# Create README.md File

echo "# $folder_" >> README.md

# Push to the Origin from Master

git add . 
git commit -m 'first commit'
git remote add origin git@github.com:$username/$folder_.git
git push -u origin master
