#! /usr/bin/env bash

# Get Username

username=""

# Get Token

token=""

# Get Folder Name

project=`basename $PWD`
project_=`echo ${project// /_}`

# Get Project Name

folder=`echo $PWD | awk -F "/" '{print$(NF-1)}'`
folder_=`echo ${folder// /_}`

# Get SDS Directory

note="# SDS_$folder_/_$project_"
note_=`echo $note | tr -d /`

# Delete Remote Repository on github.laureate.net if existed

# curl -u '$username:$token' -X "DELETE" https://github.laureate.net/api/v3/repos/Laureate/$project_

# Create Remote Repository on github.laureate.net

curl -u '$username:$token' https://github.laureate.net/api/v3/orgs/Laureate/repos -d "{\"name\":\"$project_\"}"

# Generate Local Git Repository

git init
git config user.name "jingyi-li"

# Create .gitignore File

echo 
"$note_ gitignore

# Ignore everything
*

# Whitelist anything that's a directory
!*/

# But not these files
!*.R
!*.py
!*.sql
!*.sas
!*.sh
!*.bat
!*.gitignore
!*.md" >> .gitignore

# Ignore Files w/ Size > 5M

find . -size +5M | sed 's|^\./||g' | cat >> .gitignore

# Create README.md File 

echo "$note_" >> README.md

# Push to the Origin from Master

git add . 
git commit -m 'first commit'
git remote add origin git@github.laureate.net:Laureate/$project_.git
git push -u origin master
