#! /usr/bin/env bash

project=`basename $PWD`
project_underscore=`echo ${project// /_}`
folder=`echo $PWD | awk -F "/" '{print$(NF-1)}'`
folder_underscore=`echo ${folder// /_}`

# Delete Remote Repository on github.com
curl -u 'Laureate' -X "DELETE" https://github.laureate.net/api/v3/repos/Laureate/$project_underscore

# Create Remote Repository on github.laureate.net

curl -u 'Laureate' https://github.laureate.net/api/v3/user/repos -d "{\"name\":\"$project_underscore\"}"

# Generate Local Git Repository

git init
git config user.name Laureate

# Create .gitignore File

echo "
# SDS_$folder_underscore_$project_underscore gitignore

# Ignore everything
*
# But not these files
!*.R
!*.py
!*.sql
!*.sas
!*.sh
!*.bat
!*.gitignore
!*.md
" >> .gitignore

# Ignore Files w/ Size > 5M

find . -size +5M | sed 's|^\./||g' | cat >> .gitignore

# Create README.md File 

echo "
# SDS_$folder_underscore_$project_underscore
" >> README.md

# Push to the Origin from Master
git add . 
git commit -m 'first commit'
git remote add origin git@github.laureate.net:Laureate/$project_underscore.git
git push -u origin master
